### ISSUE TITLE
Json decode error

### ISSUE THREAD

**Issue by ChaoticNPC** [TLNBS2405/heihachi#1]
I am receiving a jsonDecodeError expecting ',' delimiter line 4, column 1 (char 144)

When I run the main.py

**Comment by TLNBS2405** [comment]
Did you make any changes? Can you remove the try and except in the main.py and try again? I don't have any issues right now

**Comment by ChaoticNPC** [comment]
Without removing that I get this:

> Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/heihachi/src/main.py", line 20, in <module>
    discord_token = CONFIG_PATH.read_config()['DISCORD_TOKEN']
  File "/root/heihachi/src/module/configurator.py", line 15, in read_config
    config_data = json.load(config_json)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 336, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 352, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 1 (char 143)

When I remove it I get this:

> Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/heihachi/src/main.py", line 7, in <module>
    from src.module import util
  File "/root/heihachi/src/module/util.py", line 8, in <module>
    from src.wavu import wavu_importer
  File "/root/heihachi/src/wavu/wavu_importer.py", line 4, in <module>
    from src.wavu import wavu_reader
  File "/root/heihachi/src/wavu/wavu_reader.py", line 9, in <module>
    wavuwiki = MediaWiki(url=const.WAVU_API_URL)
  File "/usr/local/lib/python3.10/dist-packages/mediawiki/mediawiki.py", line 128, in __init__
    self._get_site_info()
  File "/usr/local/lib/python3.10/dist-packages/mediawiki/mediawiki.py", line 876, in _get_site_info
    response = self.wiki_request({"meta": "siteinfo", "siprop": "extensions|general"})
  File "/usr/local/lib/python3.10/dist-packages/mediawiki/mediawiki.py", line 866, in wiki_request
    req = self._get_response(params)
  File "/usr/local/lib/python3.10/dist-packages/mediawiki/mediawiki.py", line 992, in _get_response
    return self._session.get(self._api_url, params=params, timeout=self._timeout).json()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 336, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: cannot unpack non-iterable NoneType object

The only thing I have changed was adding the bot key in the config.json.  Otherwise everything has been left as it was downloaded.

**Comment by TLNBS2405** [comment]
Are you sure your config looks similar to this?
```
{
  "DISCORD_TOKEN": "xxxx",
  "FEEDBACK_CHANNEL_ID" : 123,
  "ACTION_CHANNEL_ID" : 456
}
```

**Comment by ChaoticNPC** [comment]
I was missing a comma after the feedback channel ID! That fixed it.
